[package]
name = "js-compiler"
version = "0.1.0"
authors = ["laegel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.regex]
version = "1.3"
default-features = false
features = ["std"]